apiVersion: apps/v1
kind: Deployment

metadata:
  name: calculator-deployment

spec:
  replicas: 10

  selector:
    matchLabels:
      app: calculator

  template:
    metadata:
      labels:
        app: calculator

    spec:
      containers:
        - name: calculator-container
          image: spring-boot-calculator:12.4
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 8080